# Generated by Django 6.0 on 2025-12-26 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bus_number', models.CharField(max_length=50)),
                ('bus_type', models.CharField(choices=[('ac_sleeper', 'AC Sleeper'), ('ac_seater', 'AC Seater'), ('non_ac_sleeper', 'Non-AC Sleeper'), ('non_ac_seater', 'Non-AC Seater'), ('volvo', 'Volvo Multi-Axle')], default='ac_seater', max_length=20)),
                ('source', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_seats', models.IntegerField(default=40)),
                ('rows', models.IntegerField(default=10)),
                ('seats_per_row', models.IntegerField(default=4)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_charging', models.BooleanField(default=True)),
                ('has_toilet', models.BooleanField(default=False)),
                ('has_water', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'db_table': 'buses',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['row', 'column'],
            },
        ),
    ]
